name: expbook
main: boardinggamer.expbook.expbook
version: 2.0.0
author: TerraNetworkOrg(orig.boardingamer)
dev-url: http://dev.bukkit.org/server-mods/tno-expbook/
description: get exp from books
softdepend: [Vault]
commands:
 expbook:
  description:
  usage: <command>
  aliases: []
permissions:
  expbook.*:
    children:
      expbook.use: true
      expbook.create: true
      expbook.command.*: true
  expbook.command.*:
    children:
      expbook.command.help: true
      expbook.command.reload: true
      expbook.command.set: true
  expbook.create:
    description: Allows you to create and destroy altars.
    default: op
  expbook.use:
    description: Allows players to use the altars.
    default: op
  expbook.command.reload:
    description: Allows player to use /expbook reload
    default: op
  expbook.command.help:
    description: Allows player to use /expbook help
    default: op
  expbook.command.set:
    description: Allows player to use /expbook set
    default: op